trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: npm install
  displayName: 'install dependencies'

- script: npm run build
  displayName: 'Build'

- script: docker login -u l3sdn -p $(password) rodacr01.azurecr.io
  displayName: 'login'

- script: docker build -t rodacr01.azurecr.io/lehu .
  displayName: 'build'

- script: docker push rodacr01.azurecr.io/lehu  
  displayName: 'push'

# - task: Docker@2
#   displayName: 'Build and push an image to container registry'
#   inputs:
#     containerRegistry: 'rodacr01.azurecr.io'
#     repository: 'VianneyLehu/l3sdn-final-project'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'
#     buildContext: '$(Build.SourcesDirectory)'