trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: npm install
  displayName: 'install dependencies'

- script: npm run build
  displayName: 'Build'


- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: 'rodacr01.azurecr.io'
    repository: 'VianneyLehu/l3sdn-final-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    buildContext: '$(Build.SourcesDirectory)'